### ISSUE TITLE
implementing transfer learning

### ISSUE THREAD

**Issue by sinadunk23** [opencv/openvino_training_extensions#115]
Hi thanks for your sharing your code.
i would like to know how i can implement transfer learning on your model and use it to detect plates of another country and language.
pointing out that i don't want to start training from scratch and want to only train the last layers on my dataset so i won't need a large dataset.

**Comment by AlexanderDokuchaev** [comment]
Hi @sinadunk23 
If you mean license plate recognition, than you should 

1. Prepare your dataset like it show in [#prepare-dataset](https://github.com/opencv/openvino_training_extensions/tree/develop/tensorflow_toolkit/lpr#prepare-dataset)
2. Download [trained checkpoint](https://download.01.org/opencv/openvino_training_extensions/models/license_plate_recognition/license-plate-recognition-barrier-0007.tar.gz)
3. Follow instruction in [readme.md](https://github.com/opencv/openvino_training_extensions/tree/develop/tensorflow_toolkit/lpr#train-and-evaluation) run `tools/train.py` with 
`--init_checkpoint <trained_checkpoint>`  

To freeze some layer you should add `trainable=False` to their initialization in [lpr/networks/lprnet.py](
https://github.com/opencv/openvino_training_extensions/blob/develop/tensorflow_toolkit/lpr/lpr/networks/lprnet.py).

**Comment by sinadunk23** [comment]
thanks for the quick reply.
could you also please tell me How and which files i'll have to edit in order to be able to use your code for other license plate formats.like if the license plates had more letters or numbers or didn't have that letter defining the city like in the chinese dataset.

**Comment by AlexanderDokuchaev** [comment]
https://github.com/opencv/openvino_training_extensions/blob/develop/tensorflow_toolkit/lpr/lpr/utils.py#L27
