### ISSUE TITLE
Train with crop image dataset

### ISSUE THREAD

**Issue by sonanui** [opencv/openvino_training_extensions#117]
I trained Global Context Module with MobileNet v1, MobileNet v2 and ShuffleNet v2 on full frame image dataset and crop human image dataset (crop from full frame image). With full frame image dataset, MobileNet v2 > MobileNet v1 > ShuffleNet v2. With crop image, MobileNet v2 > ShuffleNet v2, and better than with full frame image, but MobileNet v1, the accuracy decreases 20% :(( and lower than ShuffleNet v2. Can you help me? Why?

**Comment by AlexanderDokuchaev** [comment]
Hi @sonanui  
Which model do you use?

**Comment by sonanui** [comment]
> Hi @sonanui
> Which model do you use?

I train Human Pose Estimation with Global Context in this repo (link[Global Context for Convolutional Pose Machines](url))

**Comment by AlexanderDokuchaev** [comment]
@Daniil-Osokin  Could you help?

**Comment by Daniil-Osokin** [comment]
Hi, can you please post some examples of full-frame dataset and cropped? If two of three networks work properly on cropped dataset, then it looks like there are some errors in MobileNet v1 integration, try to check it once again.
