### ISSUE TITLE
No module named 'spatial_transformer'

### ISSUE THREAD

**Issue by sinadunk23** [opencv/openvino_training_extensions#118]
while runing the train.py file i get the following error:
ModuleNotFoundError: No module named 'spatial_transformer'

what am i missing?

**Comment by AlexanderDokuchaev** [comment]
Which model are you running?

**Comment by sinadunk23** [comment]
license plate recognition

**Comment by AlexanderDokuchaev** [comment]
You should download  submodules https://github.com/opencv/openvino_training_extensions/tree/develop/tensorflow_toolkit#setup

  ```Bash
  cd openvino_training_extensions
  git submodule update --init --recommend-shallow external/cocoapi external/models
  ```

**Comment by sinadunk23** [comment]
i get this error when doing the git submodule update --init --recommend-shallow external/cocoapi external/models
Unable to checkout 'f0899f18e178afb4b57c50ec32a7e8952e6f6a99' in submodule path 'external/models'

**Comment by sinadunk23** [comment]
i was able to work that out but now i'm getting this error:
tensorflow.python.framework.errors_impl.InvalidArgumentError: 0-th value returned by pyfunc_0 is int32, but expects int64
by the way i'm running it on windows 10

**Comment by AlexanderDokuchaev** [comment]
Unfortunately, we are not running this code on windows. 
Which version of python do you use?


And how did you solve the problem with submodule?

**Comment by sinadunk23** [comment]
but what is the difference really?shouldn't it work on both platforms?
i'm using python 3.6.
and i just removed everything and followed your instructions again and i didn't get that error about the submodules anymore.

**Comment by sinadunk23** [comment]
i also get an error while trying to load the checkpoints.
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [49] rhs shape= [71]
         [[node save/Assign_28 (defined at tools/train.py:81) ]]

Errors may have originated from an input operation.
Input Source operations connected to node save/Assign_28:
 Conv_15/biases (defined at c:\users\pc\desktop\openvino_training_extensions\tensorflow_toolkit\lpr\lpr\trainer.py:134) 
and also this:
 err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint.

**Comment by AlexanderDokuchaev** [comment]
@sinadunk23 


> but what is the difference really?shouldn't it work on both platforms?

Yes, Linux and Windows are difference systems. As result some functions can return difference result. 
In this case, difference default size for integer values.

Windows: 
```
>>> np.asarray([1,2,3]).dtype
dtype('int32')
>>> np.asarray([1.,2.,3.]).dtype
dtype('float64')
```

Linux: 
```
>>> np.asarray([1,2,3]).dtype
dtype('int64')
>>> np.asarray([1.,2.,3.]).dtype
dtype('float64')
```

Topic on stackoverflow:
https://stackoverflow.com/questions/36278590/numpy-array-dtype-is-coming-as-int32-by-default-in-a-windows-10-64-bit-machine

Try to use this: https://github.com/AlexanderDokuchaev/openvino_training_extensions/commit/6254893ab97378eedc6fab04e63f483356dbcf24
