### ISSUE TITLE
keypoints文件下的函数group_keypoints里面的参数min_paf_score=xxx值则么确定的

### ISSUE THREAD

**Issue by dreamercv** [opencv/openvino_training_extensions#120]
- [ ] I have searched the [issues](https://github.com/opencv/training_toolbox_tensorflow/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
    If you're describing a bug, tell us what should happen.
    If you're suggesting a change/improvement, tell us how it should work.

## Current Behavior
    If describing a bug, tell us what happens instead of the expected behavior.
    If suggesting a change/improvement, explain the current behavior.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
    How has this issue affected you? What are you trying to accomplish?
    Providing context helps us come up with a solution that is most useful in the real world.

## Your Environment

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
```
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```
- Python version:
- CUDA/cuDNN version:
- GPU model and memory:

    Include as many relevant details about the environment with which you experienced the bug.

**Comment by AlexanderDokuchaev** [comment]
Hi @dreamercv 
Please describe your question on English.
