### ISSUE TITLE
No images by tf pers_veh_bike in tensorboard (first time try)

### ISSUE THREAD

**Issue by vtimofeev01** [opencv/openvino_training_extensions#137]
I followed  Tensorflow [personal_vehicule_bike](https://github.com/opencv/openvino_training_extensions/tree/develop/tensorflow_toolkit/person_vehicle_bike_detector)  steps

after
```
python ./tools/create_crossroad_extra_tf_records.py \
    --train_image_dir=../../data/airport/train/ \
    --val_image_dir=../../data/airport/val/ \
    --train_annotations_file=../../data/airport/annotation_example_train.json \
    --val_annotations_file=../../data/airport/annotation_example_val.json \
    --output_dir=../../data/airport/tfrecords
```
i get tfrecords folder as it must be

after that i use

```
python ../../external/models/research/object_detection/model_main.py \
  --model_dir=./model \
  --pipeline_config_path=./configs/pipeline.config
```

and i get a /model folder, but in the model folder itselves there are no /eval_0 subfolder with "artifacts"

the "model" folder contains only

```
-rw-rw-r-- 1 imt imt       81 авг 20 22:18 checkpoint
-rw-rw-r-- 1 imt imt 23293218 авг 20 22:18 events.out.tfevents.1566328688.imt-pc
-rw-rw-r-- 1 imt imt 13164544 авг 20 22:18 graph.pbtxt
-rw-rw-r-- 1 imt imt 22992520 авг 20 22:18 model.ckpt-0.data-00000-of-00001
-rw-rw-r-- 1 imt imt    32164 авг 20 22:18 model.ckpt-0.index
-rw-rw-r-- 1 imt imt  6377804 авг 20 22:18 model.ckpt-0.meta
```
and by using
`tensorboard --logdir=./model`

i don't see like this right [tensorboard](https://github.com/opencv/openvino_training_extensions/blob/develop/tensorflow_toolkit/person_vehicle_bike_detector/tb_eval.png) image

no "image" menu

Thank You

Vasili

**Comment by AlexanderDokuchaev** [comment]
Hi @vtimofeev01 

It looks that something went wrong and the learning process did not start, as result you have only initialize checkpoint in `model` directory. 
Try to remove `model` directory`and check logs for errors.

And please provide information about your system environment:
- Python version:
- CUDA/cuDNN version:
- GPU model and memory:

And list of installed modules in venv - `pip list`
