### ISSUE TITLE
training time

### ISSUE THREAD

**Issue by jjh930910** [opencv/openvino_training_extensions#138]
i want to know training time and numbers of gpus

**Comment by AlexanderDokuchaev** [comment]
Hi @jjh930910 

Unfortunately, the feature to show remaining time estimate is not implemented for most part of models.

To control number of used gpus, you can use `CUDA_VISIBLE_DEVICES` environment variable.
For example, command line to use 3d gpus:
```
export CUDA_VISIBLE_DEVICES=2
python3 tools/train.py 
```
