### ISSUE TITLE
Is there any reference materials for NNCF?

### ISSUE THREAD

**Issue by zhang-xing** [opencv/openvino_training_extensions#144]
Hi there, 

Thanks a lot for providing NNCF tool. I am wondering whether there is any background materials for sparsity and quantization? Especially on the mathematical explanation of compression methods.
 
I have searched the [issues](https://github.com/opencv/training_toolbox_tensorflow/issues) of this repository and believe that this is not a duplicate.

Regards,
Xing

**Comment by AlexanderDokuchaev** [comment]
Hi @zhang-xing 
You can find sort description of algorithms in [pytorch_toolkit/nncf/nncf/README.md](https://github.com/opencv/openvino_training_extensions/blob/develop/pytorch_toolkit/nncf/nncf/README.md).

@AlexKoff88  Could you provide links to papers or something else that you used in NNCF?

**Comment by AlexKoff88** [comment]
There is some documentation here https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/nncf/docs as well.

**Comment by zhang-xing** [comment]
@AlexanderDokuchaev  @AlexKoff88  
Thanks a lot for your quick response and help.  I have read the links that you provide. I am wondering is there any paper or training slides?

Thanks again for the great tool. If there is no more information, the issue could be closed.

Regards,
Xing

**Comment by AlexKoff88** [comment]
Hi,

For quantization we used an approach which is similar to PACT paper. 
For RB-sparsity our method is quite similar to this one https://arxiv.org/abs/1712.01312.

We are going to do next release of NNCF this month. Please follow.

**Comment by zhang-xing** [comment]
Hi @AlexKoff88 

Thanks for your reference. I will follow.

Regards,
Xing
