### ISSUE TITLE
Error in running "security_barrier_camera_demo.exe" with my trained models

### ISSUE THREAD

**Issue by farshadopencv** [opencv/openvino_training_extensions#146]
Hi.

when I tested the _[security_barrier_camera_demo.exe](https://github.com/opencv/open_model_zoo/tree/master/demos/security_barrier_camera_demo)_ with the following argument:

`security_barrier_camera_demo.exe -m E:\models\vehicle-license-plate-detection-barrier-0106.xml   -m_lpr E:\models\license-plate-recognition-barrier-0001.xml  -i E:\models\car.bmp`

I got the following result:

```
C:\Users\ngm\Documents\Intel\OpenVINO\in\intel64\Debug>security_barrier_camera_demo.exe -m E:\models\vehicle-license-plate-detection-barrier-0106.xml   -m_lpr E:\models\license-plate-recognition-barrier-0001.xml  -i E:\models\car.bmp
[ INFO ] InferenceEngine:
        API version ............ 2.0
        Build .................. 27579
        Description ....... API
[ INFO ] Files were added: 1
[ INFO ]     E:\models\car.bmp
[ INFO ] Loading device CPU
        CPU
        MKLDNNPlugin version ......... 2.0
        Build ........... 27579

[ INFO ] Loading detection model to the CPU plugin
[ INFO ] Loading Licence Plate Recognition (LPR) model to the CPU plugin
[ INFO ] Number of InferRequests: 1
[ INFO ] Display resolution: 1920x1080
[ INFO ] Number of allocated frames: 3
[ INFO ] Resizable input with support of ROI crop and auto resize is disabled
Mean overall time per all inputs: 13585.76ms / 0.07FPS for 1 frames
Detection InferRequests usage: 100.00%
[ INFO ] Execution successful
```

Also, I successfully  trained two model named **my_plate_detector** and **my_lpr_model**,    for _license plate detection_ and _license plate recognition_ using the "[SSD Object Detection](https://github.com/opencv/openvino_training_extensions/tree/develop/tensorflow_toolkit/ssd_detector)" and "[LPRNet: License Plate Recognition](https://github.com/opencv/openvino_training_extensions/tree/develop/tensorflow_toolkit/lpr)" scripts in openvino_training_extensions on my own car and plate datasets. Both models perform perfect with python [ lpr infer_ie](https://github.com/opencv/openvino_training_extensions/blob/develop/tensorflow_toolkit/lpr/tools/infer_ie.py) and  [ssd infer_ie](https://github.com/opencv/openvino_training_extensions/blob/develop/tensorflow_toolkit/ssd_detector/tools/infer_ie.py) scripts inside openvino_training_extensions.

Now I want to run the  _security_barrier_camera_demo.exe_ with my trained models. When I pass the following arguments to cmd:

`security_barrier_camera_demo.exe -m E:\models\my_plate_detector.xml  -m_lpr E:\models\my_lpr_model.xml  -i E:\models\img.jpg`

I get the following error:

```
[ INFO ] InferenceEngine:
        API version ............ 2.0
        Build .................. 27579
        Description ....... API
[ INFO ] Files were added: 1
[ INFO ]     E:\models\img.jpg
[ INFO ] Loading device CPU
        CPU
        MKLDNNPlugin version ......... 2.0
        Build ........... 27579

[ INFO ] Loading detection model to the CPU plugin
[ INFO ] Loading Licence Plate Recognition (LPR) model to the CPU plugin
[ ERROR ] LPR should have 2 inputs
```

What does mean that "**LPR should have 2 inputs**"? Why  _security_barrier_camera_demo.exe_ can not execute my lpr model?   I want to use my trained lpr model in c++ api but I don't know how can  I overcome this error. Also, I realized that I should change  the following piece of **[net_wrappers.hpp](https://github.com/opencv/open_model_zoo/blob/ff1f46d87b11e7dbb767776f3de3f0f273b91498/demos/security_barrier_camera_demo/net_wrappers.hpp)**, in order that I use _security_barrier_camera_demo.exe_ with my own models:

```
std::string getResults(InferenceEngine::InferRequest& inferRequest) {
        static const std::vector<std::string> items = {
                "0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
                "<Anhui>", "<Beijing>", "<Chongqing>", "<Fujian>",
                "<Gansu>", "<Guangdong>", "<Guangxi>", "<Guizhou>",
                "<Hainan>", "<Hebei>", "<Heilongjiang>", "<Henan>",
                "<HongKong>", "<Hubei>", "<Hunan>", "<InnerMongolia>",
                "<Jiangsu>", "<Jiangxi>", "<Jilin>", "<Liaoning>",
                "<Macau>", "<Ningxia>", "<Qinghai>", "<Shaanxi>",
                "<Shandong>", "<Shanghai>", "<Shanxi>", "<Sichuan>",
                "<Tianjin>", "<Tibet>", "<Xinjiang>", "<Yunnan>",
                "<Zhejiang>", "<police>",
                "A", "B", "C", "D", "E", "F", "G", "H", "I", "J",
                "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T",
                "U", "V", "W", "X", "Y", "Z"
        };
```
  

Please guide me how can I use _security_barrier_camera_demo.exe_ with my trained models. Thanks a lot.

**Comment by AlexanderDokuchaev** [comment]
Hi @farshadopencv 

The `license-plate-recognition-barrier-0001` model was converted from Caffe framework and have small differences from TF model. One of this is that the model have second input, that is some relic from the training framework.

Try to use my branch from https://github.com/AlexanderDokuchaev/open_model_zoo/tree/compatibility_with_ote_model.  ` security_barrier_camera_demo` have been modified to works with the model from   openvino_training_extensions.

**Comment by farshadopencv** [comment]
@AlexanderDokuchaev  Thanks so much. now it works fine with my trained models.
