### ISSUE TITLE
Request for c++ version of LPRNet infer_ie 

### ISSUE THREAD

**Issue by farshadopencv** [opencv/openvino_training_extensions#148]
Hi,

I trained an LPR model with  [openvino_training_extensions](https://github.com/opencv/openvino_training_extensions/tree/develop/tensorflow_toolkit/lpr) and I successfully tested it with python lpr [infer_ie](https://github.com/opencv/openvino_training_extensions/blob/develop/tensorflow_toolkit/lpr/tools/infer_ie.py). Now I want to use this model in a c++ API. Is there any c++ version of lpr  [infer_ie](https://github.com/opencv/openvino_training_extensions/blob/develop/tensorflow_toolkit/lpr/tools/infer_ie.py) which can get a plate image and return its plate number? Thank you so much and any suggestions would be greatly appreciated.

**Comment by AlexanderDokuchaev** [comment]
Hi @farshadopencv 

Look at [Lpr class from security_barrier_camera_demo](https://github.com/AlexanderDokuchaev/open_model_zoo/blob/compatibility_with_ote_model/demos/security_barrier_camera_demo/net_wrappers.hpp#L211), it should meet your requirements.

**Comment by farshadopencv** [comment]
> Hi @farshadopencv
> 
> Look at [Lpr class from security_barrier_camera_demo](https://github.com/AlexanderDokuchaev/open_model_zoo/blob/compatibility_with_ote_model/demos/security_barrier_camera_demo/net_wrappers.hpp#L211), it should meet your requirements.

Thanks a lot. I made that successfully.
