### ISSUE TITLE
can I get inference speed up if I export a quantized model to ONNX and inference in ONNX 

### ISSUE THREAD

**Issue by WilliamZhaoz** [opencv/openvino_training_extensions#149]
if I export a quantized moedel to ONNX, and then inference in ONNX, can I get inference spped up? 
I put forward this question because I know many quantization framework just only simulate the quantization but can not bring any inference speed up, but I expect a real inference speed up during inference model in ONNX.
Thank you.

**Comment by WilliamZhaoz** [comment]
Thank you Alexander, 
So you means that, even if I get a quantized model, but I still can not accelerate inference speed e.g. on a Intel Xeon cpu even using OpenVino?

**Comment by AlexanderDokuchaev** [comment]
@WilliamZhaoz
On the contrary, you should have device, like Intel Xeon, that supports low-precision computations. 
For example, all Intel Core i7 until 10-gen do not support.

**Comment by WilliamZhaoz** [comment]
Hi Alexander,
If I use OpenVino to inference my model, and run it on a Xeon cpu device,
can I get inference speed up from quantization?
Thank you!


Alexander Dokuchaev <notifications@github.com> 于2019年9月26日周四 下午5:43写道：

**Comment by AlexanderDokuchaev** [comment]
@WilliamZhaoz Yes. but with some conditions.
Here you will find the detailed information:
- https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/nncf/nncf
- https://docs.openvinotoolkit.org/latest/_docs_IE_DG_Int8Inference.html
- https://software.intel.com/en-us/articles/lower-numerical-precision-deep-learning-inference-and-training?elq_cid=5653893&erpm_id=8668975

And you may also be interested in [calibration tool](https://docs.openvinotoolkit.org/latest/_inference_engine_tools_calibration_tool_README.html) (quanitization without fine-tuning).

**Comment by WilliamZhaoz** [comment]
Thanks for your information Alexander,
 When I convert my own onnx model to IR, I got a ERROR:
There is no registered "infer" function for node "270" with op = "Sqrt".
Please implement this function in the extensions.
How can I fix it? which op can I use that supported by OpenVINO and is
equivalent with Sqrt?
Thanks.

Alexander Dokuchaev <notifications@github.com> 于2019年9月26日周四 下午9:32写道：

**Comment by WilliamZhaoz** [comment]
I solved the problem by replacing the Sqrt by **0.5, now the op OpenVINO
does not support is ConstantOfShape as blew.

There is no registered "infer" function for node "399" with op =
"ConstantOfShape". Please implement this function in the extensions.

How can I solve this? Please tell me if you have any thoughts.

Zhiyuan Zhao <zhiyuan.zhaochn@gmail.com> 于2019年9月27日周五 下午4:40写道：

**Comment by AlexanderDokuchaev** [comment]
@WilliamZhaoz This function will added in next release of OpenVINO 2019R3, it will be available on this or next week.
Or you can try to downgrade version of the model by  https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#converting-version-of-an-onnx-model-within-default-domain-aionnx
