### ISSUE TITLE
person-reidentification-retail

### ISSUE THREAD

**Issue by dinara92** [opencv/openvino_training_extensions#159]
First of all, thank you very much for open sourcing this repo.

I have a question about pytorch_toolkit/face_recognition/* code.

I would like to re-train (and/or fine-tune) a "[person-reidentification-retail](https://docs.openvinotoolkit.org/2019_R1/_person_reidentification_retail_0079_description_person_reidentification_retail_0079.html)" Openvino model, on a custom dataset (along with Market1501 dataset).
I know that it uses [RMNet](https://arxiv.org/pdf/1812.02465.pdf) as a backbone, same as "[face-recognition-model](https://docs.openvinotoolkit.org/2019_R1/_face_reidentification_retail_0095_description_face_reidentification_retail_0095.html)".

I wonder if I can use code in pytorch_toolkit/face_recognition/* for this purpose.

**Comment by AlexanderDokuchaev** [comment]
Hi @dinara92 

Unfortunately, [person-reidentification-retail-0079](https://docs.openvinotoolkit.org/2019_R1/_person_reidentification_retail_0079_description_person_reidentification_retail_0079.html) model was trained in Caffe and we dont planing to provide training code and checkpoint for this model.

To train person-reid by using [pytorch_toolkit/face_recognition](https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/face_recognition) code is possible but you should create CustomDataset class (like [this](https://github.com/opencv/openvino_training_extensions/blob/develop/pytorch_toolkit/face_recognition/datasets/megaface.py)) without alignment by landmarks and remove all code that use landmarks in all other places.

To select `RMNet` backbone you should use '--model rmnet' argument.

**Comment by dinara92** [comment]
many thanks for a thorough reply!
As I found in [this feed](https://github.com/opencv/open_model_zoo/issues/439), I assume RMNet model pre-trained on the OpenImage dataset may not be released?

**Comment by AlexanderDokuchaev** [comment]
This is true for now :disappointed:

**Comment by whatisor** [comment]
> @dinara92 Some good news, we are planning publish code to train person-reid model in near future.

When will it come true?

**Comment by AlexanderDokuchaev** [comment]
@dinara92 @whatisor 
[pytorch_toolkit/person_reidentification](https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/person_reidentification)
