### ISSUE TITLE
About NNFC pre-trained model

### ISSUE THREAD

**Issue by FengYen-Chang** [opencv/openvino_training_extensions#173]
**Describe the bug**

I tried to download the int8 model from [here](https://download.01.org/opencv/openvino_training_extensions/models/nncf/resnet50_imagenet_int8.pth). But not sure what happened, I can't download it by wget, curl, or browser. I think it might be the file size is too large since I can download another file which is small.

**Environment:**
 - OS: Linux Ubuntu 16.04

**Comment by AlexanderDokuchaev** [comment]
:disappointed_relieved: our storage looks bad

Temporal link for file: https://drive.google.com/open?id=1_1MdjYTxp-P2ah_vOZ_yh2cK6R6s5Lfa

**Comment by FengYen-Chang** [comment]
It's ok. Thanks a lot. :)
