### ISSUE TITLE
How to generate the Synthetic Chinese License Plates dataset?

### ISSUE THREAD

**Issue by ysc703** [opencv/openvino_training_extensions#177]
Thanks.

**Comment by AlexanderDokuchaev** [comment]
Hi @ysc703 
Thank you for your interest in our project.
Unfortunately, it's lost technology of ancient civilization. On current moment we have only generated images without code. :disappointed: 

Sometime we will re-implemented it but not any time soon.

**Comment by ysc703** [comment]
@AlexanderDokuchaev Thanks^_^
