### ISSUE TITLE
LPRNet into Caffe

### ISSUE THREAD

**Issue by borisgribkov** [opencv/openvino_training_extensions#188]
Dear Intel team, first of all thanks for your work and provided code!
I would like to ask about LPRNet tensorflow model, did anyone try to convert it to caffe? If yes, what is the best tool to do it? Thanks! Or maybe it's possible to get protofile somewhere.

**Comment by AlexanderDokuchaev** [comment]
Hi @borisgribkov 
> I would like to ask about LPRNet tensorflow model, did anyone try to convert it to caffe?

No, we do not use this way. And more, we dont use Caffe anymore. 
May I ask why can't you train and use TensorFlow model?


> Or maybe it's possible to get protofile somewhere. 

You can find deploy prototxt in [open_model_zoo](https://github.com/opencv/open_model_zoo/tree/master/models/intel/license-plate-recognition-barrier-0001), but you need have implementation of CTCGreedyDecoder layer to train in Caffe.

Also recommend you use [OpenVINO toolkit](https://software.intel.com/en-us/openvino-toolkit?cid=sem&source=sa360&campid=2019_q2_cvcg_us_cvcgvcp_cvcgtdds_awa_google_text-link_generic_bmm_cd_dpdvcp_distributionofopenvino_O-1L4M8_google&ad_group=intel_div_dpd_us_openVINO&intel_term=%2Bopen+%2Bvino&sa360id=43700033924626467&gclid=EAIaIQobChMIyKL6lK2e5gIVFuDtCh2n1gQIEAAYASAAEgKRsPD_BwE&gclsrc=aw.ds) to inference your mode. Caffe and TF frameworks are supported.:smirk:

**Comment by borisgribkov** [comment]
Hi @AlexanderDokuchaev 
Thanks for your answer, it helps a lot!
To answer your questions, I want to make some tests with LPRNet and for me it's much easier to do it in Caffe because we used it previously and a lot of instruments have been developed for Caffe.  So it's easier to transfer the model instead of transfer the code to TensorFlow. 
I understand about OpenVINO, but we traditionally focused of GPU.... maybe in future.

And finally, regarding CTCGreedyDecoder, did you use it together with the CTC Loss for training or it's necessary to use it only during inference?
Thanks for your help!

**Comment by AlexanderDokuchaev** [comment]
@borisgribkov 
> Caffe because we used it previously and a lot of instruments have been developed for Caffe. So it's easier to transfer the model instead of transfer the code to TensorFlow.
I understand about OpenVINO, but we traditionally focused of GPU.... maybe in future.

Time to changes :smirk:

> And finally, regarding CTCGreedyDecoder, did you use it together with the CTC Loss for training or it's necessary to use it only during inference?

It was so long ago... i cant find train.prototxt, but looks like CTCLoss is used with CTCGreedyDecoder.

**Comment by borisgribkov** [comment]
@AlexanderDokuchaev Thanks a lot! Regarding CTC I will check in TensorFlow.

**Comment by borisgribkov** [comment]
@AlexanderDokuchaev Thanks again, as I found GreedyDecoder layer is a some kind of post-processing, no need to use it for training, I have reproduced your TensorFlow result in Caffe using CTC Loss, at the moment without ST layer, will add it. Postprocessing step could be implemented independently.

**Comment by lswgh** [comment]
same problem , have you converted the LPRNET  to caffe model?
THANKS FOR ANY REPLAY!

**Comment by lswgh** [comment]
@borisgribkov  have you converted the LPRNET to caffe ? i want to do the same job as well!

**Comment by borisgribkov** [comment]
@lswgh Sorry for the delay. As far as I remember I did't finish with the conversion, but you don't need it. The idea of the model is character sequence recognition, but without traditionally used LSTM recurrent layers, and that is all. So, you can take something like this https://github.com/yalecyu/crnn.caffe/tree/master/examples/crnn and simply exchange two LSTM layer in the end with a convolution layer. Loss layer ( CTC loss ) is the same in the both cases. Regarding post-processing step, I guess you can find it in the code above.
