### ISSUE TITLE
lprnet - please explain config.py parameters

### ISSUE THREAD

**Issue by hlacik** [opencv/openvino_training_extensions#199]
Hello guys,

would you be so kind to describe what the following configuration parameters do in lprnet

`input_shape = (24, 114, 3)  # (height, width, channels)
use_h_concat = False
use_oi_concat = False
max_lp_length = 20
rnn_cells_num = 128`

I do understand input shape, however not sure what is the best practice for max_lp_length vs rnn_cells_num, in some papers max_lp_length should be twice of real max size (example my max is 8, so i use 16). Also rnn_cells_nums are somehow related to number of characters (decode_beans) ? So if I have [A-Z0-9] which is 36 chars, could i set rnn_cells_num to 36?

Thanks in advance!

**Comment by AlexanderDokuchaev** [comment]
Hi @hlacik 

> max_lp_length vs rnn_cells_num, in some papers max_lp_length should be twice of real max size (example my max is 8, so i use 16)

Yes it's correct.

> Also rnn_cells_nums are somehow related to number of characters (decode_beans) ? So if I have [A-Z0-9] which is 36 chars, could i set rnn_cells_num to 36?

`rnn_cells_nums` is not strictly related to number of characters. 
You can try to change rnn_cell_num, but better try to train model with original parameters and only then try to find the best model parameters.

**Comment by hlacik** [comment]
Thanks!
