### ISSUE TITLE
New person re-identification models

### ISSUE THREAD

**Issue by dinara92** [opencv/openvino_training_extensions#200]
My question in regarding new reid models (acc.to [configs](https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/person_reidentification/config)) based on torchreid project's OSNet.
Can you give a reference on [FPN class](https://github.com/opencv/openvino_training_extensions/blob/develop/pytorch_toolkit/person_reidentification/models/modules/fpn.py#L92)? How are [these models](https://github.com/opencv/openvino_training_extensions/blob/develop/pytorch_toolkit/person_reidentification/models/builder.py#L28) different from original osnet_x1_0?

**Comment by AlexanderDokuchaev** [comment]
@sovrasov @DmitriySidnev

**Comment by DmitriySidnev** [comment]
@dinara92,
Difference from original OSNet - FPN. Where it is and how is used you can find [here](https://github.com/opencv/openvino_training_extensions/blob/develop/pytorch_toolkit/person_reidentification/models/osnet_fpn.py). Shortly, we just add [FPN](https://arxiv.org/abs/1612.03144) to OSNet.
