### ISSUE TITLE
infer_ie.py couldn't compatible with CAFFE trained model in LPR

### ISSUE THREAD

**Issue by SueeH** [opencv/openvino_training_extensions#201]
Hi  In tensorflow_toolkit/lpr/tools 
When I run  '$python  infer_ie.py'  with ‘.bin’ convert from tensorflow frozen file，run Ok. 
But when run '$python infer_ie.py' with  ‘.bin’ downloaded from model zoo(trained by CAFFE), some error message as follows:
dict_keys(['seq_ind', 'data'])
**_Traceback (most recent call last):
  File "tools/infer_ie.py", line 129, in <module>
    sys.exit(main() or 0)
  File "tools/infer_ie.py", line 102, in main
    args.plugin_dir, args.cpu_extension)
  File "tools/infer_ie.py", line 84, in load_ir_model
    assert len(net.inputs.keys()) == 1, "LPRNet must have only single input"
AssertionError: LPRNet must have only single input**

I have checked #146 ，which tells me some difference between CAFFE trained model and tensorflow trained model, and also c++ compatible code is available in #146 
If test CAFFE trained model with python, how to modify the infer_ie.py to compatible with CAFFE trained model ?
Thanks in advance !

**Comment by AlexanderDokuchaev** [comment]
Hi @SueeH 
Take [infer_ie.py](https://github.com/AlexanderDokuchaev/openvino_training_extensions/blob/lpr_infer_ir_from_caffe/tensorflow_toolkit/lpr/tools/infer_ie.py) from my branch.
[diff](https://github.com/AlexanderDokuchaev/openvino_training_extensions/commit/feef533bc7e68de8e755189c02af17812db24e0e)

**Comment by SueeH** [comment]
> Hi @SueeH
> Take [infer_ie.py](https://github.com/AlexanderDokuchaev/openvino_training_extensions/blob/lpr_infer_ir_from_caffe/tensorflow_toolkit/lpr/tools/infer_ie.py) from my branch.
> [diff](https://github.com/AlexanderDokuchaev/openvino_training_extensions/commit/feef533bc7e68de8e755189c02af17812db24e0e)
Thanks very much！
run successfully!
