### ISSUE TITLE
The result is wrong when I use IR format to infer

### ISSUE THREAD

**Issue by lemonyhw** [opencv/openvino_training_extensions#222]
Thank you for project. I have a problem with person redientification.
First, I use the  ./config/person-reidentification-retail-0200.yaml to train my model.
Then,  I convert the PyTorch model to the ONNX format and Convert the obtained ONNX model to the IR format. When I used PyTorch model and IR format model to infer, I both got the right result. 

The problem was if I just modified the param fpn in ./config/person-reidentification-retail-0200.yaml to False, When I used Pytorch model and IR format model to infer, I got the right result for the former and got the wrong result for the later.

The former result 
Computing CMC and mAP ...
** Results **
mAP: 91.85%
CMC curve
Rank-1  : 96.76%
Rank-5  : 99.17%
Rank-10 : 99.47%
Rank-20 : 99.70%

The later result
Computing CMC and mAP ...
** Results **
mAP: 2.11%
CMC curve
Rank-1  : 6.62%
Rank-5  : 15.44%
Rank-10 : 21.32%
Rank-20 : 28.09%

my test code is
{python main.py \
    --root ./dataset/ \
    --config ./config/person-reidentification-retail-0200.yaml\
    test.evaluate True}

Why? How to solve it?

**Comment by AlexanderDokuchaev** [comment]
@sovrasov @DmitriySidnev Could you help?

**Comment by DmitriySidnev** [comment]
@lemonyhw, hi!

Could you please share full log of conversion to ONNX and IR formats? If it is possible to share weights of your model I would try to check the conversion process for this case. Do you use commands for conversion from readme?

**Comment by DmitriySidnev** [comment]
@lemonyhw, and one more question: do you use the latest version of a develop branch?

**Comment by lemonyhw** [comment]
> @lemonyhw, and one more question: do you use the latest version of a develop branch?

I installed the develop branch last month and maybe there something has been updated. So I am going to update the latest version of a develop branch and try it again. If  I confront the same problem, I will ask for your help again. Thank you very much~

**Comment by DmitriySidnev** [comment]
@lemonyhw, some days ago there was a [fix](https://github.com/opencv/openvino_training_extensions/pull/219/commits/d7ca82511f7a98984c2447f26c9648316cc4cfce) for ONNX converter.

**Comment by lemonyhw** [comment]
> @lemonyhw, some days ago there was a [fix](https://github.com/opencv/openvino_training_extensions/pull/219/commits/d7ca82511f7a98984c2447f26c9648316cc4cfce) for ONNX converter.

Yes，I was happy that my problem was solved after I updated the latest version of a develop branch yesterday. Maybe there is something wrong in old version. Thank you very much~~~

**Comment by DmitriySidnev** [comment]
@AlexanderDokuchaev, I think this issue can be closed.
