### ISSUE TITLE
Unexpected Error log when running nosetests in https://github.com/opencv/training_toolbox_tensorflow

### ISSUE THREAD

**Issue by luweizhou2016** [opencv/openvino_training_extensions#23]
After setting up and running nosetests, there would be below error log printing out:
**2018-12-03 07:29:03.768323: E tensorflow/stream_executor/cuda/cuda_driver.cc:397] failed call to cuInit: CUDA_ERROR_NO_DEVICE**

It seems that GPU is not probed successfully. Tried many ways and can't make the error log disappearing. 
BTW, I can run the COCO training with GPU as the steps of training_toolbox_tensorflow.  
 

- [ ] I have searched the [issues](https://github.com/opencv/training_toolbox_tensorflow/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
No error log and Nvidia GPU can be probed automatically.

## Current Behavior
Print error log and can't probe the Nvidia GPU after tries.
## Steps to Reproduce (for bugs)

1. Just follow the steps of https://github.com/opencv/training_toolbox_tensorflow. run the "nosetests"

## Context
    How has this issue affected you? What are you trying to accomplish?
    Providing context helps us come up with a solution that is most useful in the real world.

## Your Environment

Ubuntu 16.04 with Cuda 9.0.  nvidia-smi can also work.

**Comment by luweizhou2016** [comment]
So , the nosetests is expected to only run on CPU, right?
The test result is okay. Just the Error logging makes me confused.

**Comment by alexey-sidnev** [comment]
Yes, you are right! Only on CPU. The main problem with execution on GPU (typical for parallel calculations) is slightly different results on the same input data.
Anyway, I agree with you. Error during test looks very strange, so we will think about the suppressing of this error.
