### ISSUE TITLE
Single Human Pose: no stage_4_output_1_heatmaps layer in pre-trained COCO dataset

### ISSUE THREAD

**Issue by cansik** [opencv/openvino_training_extensions#233]
I have tried to run the [pretrained COCO model](https://github.com/opencv/openvino_training_extensions/blob/develop/pytorch_toolkit/human_pose_estimation/README_single.md#pretrained-model-) within OpenCV DNN. For that I have converted the `single-human-pose-estimation-0001.pth` to the ONNX format by using following script (size parameter as mentioned for COCO trained models).

```bash
python convert_to_onnx.py --checkpoint-path single-human-pose-estimation-0001.pth --single-person --input-size 384 288
```

Interestingly, the output of this script tells me the valid output layers:

```
...
  %429 : Float(1, 128, 48, 36) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[1, 1], pads=[0, 0, 0, 0], strides=[1, 1]](%428, %282, %283), scope: SinglePersonPoseEstimationWithMobileNet/RefinementStage/Sequential[heatmaps]/Sequential[0]/Conv2d[0]
  %430 : Float(1, 128, 48, 36) = onnx::Relu(%429), scope: SinglePersonPoseEstimationWithMobileNet/RefinementStage/Sequential[heatmaps]/Sequential[0]/ReLU[1]
  %stage_1_output_1_heatmaps : Float(1, 17, 48, 36) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[1, 1], pads=[0, 0, 0, 0], strides=[1, 1]](%430, %284, %285), scope: SinglePersonPoseEstimationWithMobileNet/RefinementStage/Sequential[heatmaps]/Sequential[1]/Conv2d[0]
  return (%stage_0_output_1_heatmaps, %stage_1_output_1_heatmaps);
}
```

So only `stage_0_output_1_heatmaps` and `stage_1_output_1_heatmaps` are output layers. Looking at the documentation, this tells me that I am working with a ** LIP** dataset, instead of a COCO dataset. There is of course an error too in OpenCV, when I try to forward with `stage_4_output_1_heatmaps`.

Is it possible that you accidentally mis-labeled the pre-trained dataset?

**Comment by AlexanderDokuchaev** [comment]
Hi @cansik 
Thank you for your interest in our project. 

`convert_to_onnx.py` created model with 1 refinement-stages and ignored other stages from pretrained snapshot.

Update repository to latest commit and run [follow command](https://github.com/opencv/openvino_training_extensions/blob/develop/pytorch_toolkit/human_pose_estimation/README_single.md#conversion-to-openvino-format-1):

```
python scripts/convert_to_onnx.py --checkpoint-path <CHECKPOINT> \
    --single-person \
    --output-name single-human-pose-estimation.onnx \
    --input-size 384 288 \
    --mode-interpolation nearest \
    --num-refinement-stages 4
```

In output you will have onnx model with output 'stage_4_output_1_heatmaps'

**Comment by cansik** [comment]
Yes this works now. Thank you very much!
