### ISSUE TITLE
How to extract scale factor of weight quantization

### ISSUE THREAD

**Issue by JonasNey** [opencv/openvino_training_extensions#234]
Hello!

I used nncf to train a quantized model with the goal of implementing it, using HLS and C++, on an FPGA. 
To implement inference on the FPGA I need to get the values of the conv layer weights. This is no problem, I just access the layers in pytorch and write the weights to a file. But those weights don't seem to be quantized. 
How to get the quantized weights and the scale factor of symmetric quantization out of a trained model?
Additionally, I tried to export it to onnx format but get an error, because of max-unpooling layer, that doesn't seem to be resolved yet: [https://github.com/pytorch/pytorch/issues/25088
](url)

Thanks for any help!

**Comment by AlexanderDokuchaev** [comment]
@AlexKoff88

**Comment by AlexKoff88** [comment]
Hi,

Regarding the max-unpooling problem. I suggest changing the FP32 model to be able to export to ONNX, the possible options are to replace this layer by deconvolution or upsampling (e.g. bilinear).

As for the quantization of weights and activations, here we represent everything in FP32 precision with the rules on how to interpret the model as the low-precision one. Shortly, we insert FakeQuantize operations in the graph which is, de-facto, a combination of two operations Quantize and Dequantize. So the interpreting rules include splitting all the FakeQuantizes, quantizing weights and keeping quantize operations for activations, and propagating Dequntize after the Conv, FC, etc.
Then you can replace FP32 operations by their integer analogs, merge Dequantize+Quantize into the Requantize and so on.

For more details, please refer to the following resources:
- https://www.intel.ai/open-vino-low-precision-pipeline/
- https://arxiv.org/pdf/2002.08679v2.pdf
- https://arxiv.org/pdf/1712.05877.pdf and corresponding QAT resources from google

**Comment by JonasNey** [comment]
Thanks for the fast reply!

> Regarding the max-unpooling problem. I suggest changing the FP32 model to be able to export to ONNX, the possible options are to replace this layer by deconvolution or upsampling (e.g. bilinear).

I also thought about that, but unfortunately this reduces accuracy.

I forgot to mention that I don't use the openvino toolkit at all. I just use nncf as standalone package in my custom training pipeline. 

I understand that the trained weights are floating point and need to be converted to integer using the quantization rules. 
But I'm not sure how to use requantize function in a custom pipeline. I could also implement it by myself but somehow I need access to the quantization varibales like "scale", "input_high", "input_low" etc. 
Maybe the approach to use nncf for inference without openvino toolkit is completely wrong and I should go in a different direction? If that is the case you can close the issue and I'll search for another solution.

**Comment by AlexKoff88** [comment]
@JonasNey, sorry but we don't consider any other inference paths except OpenVINO.
