### ISSUE TITLE
LprNet

### ISSUE THREAD

**Issue by richardgohth** [opencv/openvino_training_extensions#238]
Have been trying to train Lprnet
but there are lots of incorrect reads.
HOw can we get the "confidence" of the read?
Thanks
-Newbie

**Comment by AlexanderDokuchaev** [comment]
Hi @richardgohth 
Unfortunately, you cant get it. CTCGreedyDecoder that used in LPR model have no "confidence" in output.

**Comment by richardgohth** [comment]
Thanks
