### ISSUE TITLE
mo.py not found?

### ISSUE THREAD

**Issue by richardgohth** [opencv/openvino_training_extensions#256]
Why is tensorflow ssd detector being abandoned?
We have invested much resources and have installed base,
please do reconsider supporting this.

when exporting the model we had the following error.
===========
mo.py --framework=tf --input_model=model/export/frozen_graph/graph.pb.frozen --output_dir=model/export/IR/FP32 --model_name=vlp --output=ssd_heads/concat_reshape_softmax/mbox_loc_final,ssd_heads/concat_reshape_softmax/mbox_conf_final,ssd_heads/concat_reshape_softmax/mbox_priorbox --input_shape=[1,256,256,3] --scale=127.5 --mean_value=[127.5,127.5,127.5] --tensorflow_use_custom_operations_config=model/export/frozen_graph/graph.tfmo.json --data_type=FP32
Traceback (most recent call last):
  File "tools/export.py", line 117, in <module>
    tf.app.run(main)
  File "/deeplearning/openvino_training_extensions/tensorflow_toolkit/ssd_detector/venv/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "tools/export.py", line 112, in main
    execute_mo(mo_params, frozen_graph, export_dir)
  File "/deeplearning/openvino_training_extensions/tensorflow_toolkit/utils/tfutils/helpers.py", line 222, in execute_mo
    subprocess.call(command)
  File "/usr/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mo.py': 'mo.py'

**Comment by AlexanderDokuchaev** [comment]
Hi @richardgohth 
> FileNotFoundError: [Errno 2] No such file or directory: 'mo.py': 'mo.py'

You need set up OpenVINO environment variables
```
source $INTEL_OPENVINO_DIR/bin/setupvars.sh
```
INTEL_OPENVINO_DIR is `/opt/intel/openvino` or `/home/$USER/intel/openvino`, it depends from your type of your installation OpenVINO toolkit as sudo for all user or only for current user.

> Why is tensorflow ssd detector being abandoned?
We have invested much resources and have installed base,
please do reconsider supporting this.

Don`t worry about support, It's not abandoned, OpenVINO will support it. But it is not recommended to use at start of project as code to training new model. Of course if you will have any question or problems we will help you.

On current moment tensorflow ssd detector is outdated. If you will try to use mmdetection on pytorch you can get better model for less time (better optimization of training process and better final metrics).

**Comment by richardgohth** [comment]
Thanks for your help.
Owe you a cuppa when you are here when covid goes away.
Much relief support is not discrupted. Thank you.
