### ISSUE TITLE
Unknown Layer Type: CTCGreedyDecoder

### ISSUE THREAD

**Issue by richardgohth** [opencv/openvino_training_extensions#265]
Hi
Having above run time error when running below,
Appreciate any advise,
thank you
===============================================
C:\Users\optasia\Documents\Intel\OpenVINO\inference_engine_demos_build\intel64\Release>security_barrier_camera_demo  -d GPU -d_va  GPU -d_lpr  GPU  -m vehicle-license-plate-detection-barrier-0106.xml  -m_lpr license-plate-recognition-barrier-0001.xml   -i "rtsp://root:opt12345@192.168.1.93/live.sdp" -display_resolution 1200x980
[ INFO ] InferenceEngine:
        API version ............ 2.1
        Build .................. 32974
        Description ....... API
[ INFO ] Files were added: 1
[ INFO ]     rtsp://root:opt12345@192.168.1.93/live.sdp
[ INFO ] Loading device GPU
        GPU
        clDNNPlugin version ......... 2.1
        Build ........... 32974

[ INFO ] Loading detection model to the GPU plugin
[ INFO ] Loading Licence Plate Recognition (LPR) model to the GPU plugin
[ ERROR ] Unknown Layer Type: CTCGreedyDecoder

**Comment by AlexanderDokuchaev** [comment]
Hi @richardgohth 
GPU plugin does not support CTCGreedyDecoder. 
I don't know details but maybe you can solve this issue by [Custom Layer GPU Extension](https://docs.openvinotoolkit.org/latest/_docs_HOWTO_Custom_Layers_Guide.html).
Ask about it in https://github.com/opencv/open_model_zoo.

**Comment by richardgohth** [comment]
Noted with thanks
