### ISSUE TITLE
Saving results of test_exported.py 

### ISSUE THREAD

**Issue by js333031** [opencv/openvino_training_extensions#286]
Question on the Validation step of https://github.com/opencv/openvino_training_extensions/blob/develop/pytorch_toolkit/object_detection/person_vehicle_bike_detection.md, 

How can I save inference results with annotations/bounding-boxes into a jpeg/png file?

**Comment by js333031** [comment]
Additional question... I tried the trained model with crossroad_camera_demo but got following error. Same demo, with pre-trained model works...

c:\Intel\OpenVINO\omz_demos_build\intel64\Release>crossroad_camera_demo.exe -m <path>\person-vehicle-bike-detection-crossroad-1016.xml
InferenceEngine: 00007FFA274F4020
[ INFO ] Parsing input parameters
[ INFO ] Reading input
[ INFO ] Person Attributes Recognition detection DISABLED
[ INFO ] Person Reidentification Retail detection DISABLED
[ INFO ] Loading device CPU
        CPU
        MKLDNNPlugin version ......... 2.1
        Build ........... 42025

[ INFO ] Loading network files for PersonDetection
[ INFO ] Batch size is forced to  1
[ INFO ] Checking Person Detection inputs
[ INFO ] Checking Person Detection outputs
[ WARN:0] global C:\jenkins\workspace\OpenCV\OpenVINO\2020.2\build\windows\opencv\modules\videoio\src\cap_msmf.cpp (436) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
[ ERROR ] Person Detection network should have only one output

C:\

**Comment by Ilya-Krylov** [comment]
you should export your model with **--alt_ssd_export** option

python ../../external/mmdetection/export.py config.py snapshot.pth export_dir openvino **--alt_ssd_export**

**Comment by js333031** [comment]
Thank you. With --alt_ssd_export option, the crossroad_camera_demo.exe runs. However, nothing is detected. I used image_000002.jpg as input image provided in validation data set of this repo: https://github.com/opencv/openvino_training_extensions/blob/develop/data/airport/val/image_000002.jpg
