### ISSUE TITLE
Detectron2 trained model support

### ISSUE THREAD

**Issue by junxnone** [opencv/openvino_training_extensions#288]
Thanks for share awesome project.

---
**openvino_training_extensions/pytorch_toolkit/instance_segmentation**

- As Detectron and maskrcnn-benchmark all are deprecated.
- I trained my model with Detectron2, but when I convert it to OpenVINO model, it is too difficult for me to figure out the problem.
- And I see the Detectron2 docs says `they are not compatible with Detectron and maskrcnn-benchark`

**So just want to know is there a plan to support Detectron2 ?**

**Comment by druzhkov-paul** [comment]
@junxnone Not sure about Detectron2 support in the nearest future, but we're adding support for (a bit customized) [mmdetection](https://github.com/opencv/mmdetection). It has even more pre-trained instance segmentation models.
