### ISSUE TITLE
How to train ssd_detector on mult-GPUs? 

### ISSUE THREAD

**Issue by SueeH** [opencv/openvino_training_extensions#292]
Thanks for sharing such a greatful project.
When training vehicle & plate ssd_detector , I tried change 'CUDA_VISIBLE_DEVICES' in vlp/config to '0,1,2,3', I found only CPU 0 was used,  GPU 1,2,3 just occupied little memory, but does not participated in calculaion.
![image](https://user-images.githubusercontent.com/28698695/81277060-74558300-9086-11ea-87d8-64a99168e848.png)

By checking tensorflow doc, I added 'train_distribute' = 'MirroredStrategy' in estimator.RunConfig,  when train with Estimator.train, and  there is another problem, the  tf.data.Dataset is needed by input_fn func, but not two tensor used now. 
I am confused with this, any one know how to modify the output of 'input_fn' to support mult gpus training ?
![image](https://user-images.githubusercontent.com/28698695/81276294-64896f00-9085-11ea-8bea-2d37810ff3bc.png)

traing logs:
![image](https://user-images.githubusercontent.com/28698695/81277278-c5fe0d80-9086-11ea-8496-14b7ee671bb9.png)

**Comment by AlexanderDokuchaev** [comment]
Hi @SueeH 
I'm not sure that multi gpu is correctly supported by ssd_detector.
We recommend use [pytorch_toolkit/object_detection](https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/object_detection) for object detection tasks. It based on [mmdetection](https://github.com/open-mmlab/mmdetection), has better performance and metrics.
