### ISSUE TITLE
Custom pytorch install for Text Spotting

### ISSUE THREAD

**Issue by ankitbansal811** [opencv/openvino_training_extensions#298]
**Installing custom pytorch fails in pytorch-text spotting**

Setting up the [environment](https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/text_spotting#installation) to train text spotting model on custom images. Environment setup fails at the sub-module clone [step](https://github.com/opencv/openvino_training_extensions/blob/develop/pytorch_toolkit/text_spotting/init_venv.sh#L25). Without setting up the environment I can not build the custom pytorch needed for text spotting model training. 

A small snip from the error is as follow:
`
Cloning into '/home/abansal4/mount_disk/openvino_training_extensions/pytorch_toolkit/text_spotting/venv/pytorch/third_party/zstd'...
fatal: remote error: upload-pack: not our ref b28816293c9098bb86457d297163d2e245853521
fatal: The remote end hung up unexpectedly
Fetched in submodule path 'android/libs/fbjni', but it did not contain b28816293c9098bb86457d297163d2e245853521. Direct fetching of that commit failed.
Building wheel torch-1.3.0a0+487bf45
-- Building version 1.3.0a0+487bf45
Could not find /home/abansal4/mount_disk/openvino_training_extensions/pytorch_toolkit/text_spotting/venv/pytorch/third_party/gloo/CMakeLists.txt
Did you run 'git submodule update --init --recursive'?
~/mount_disk/openvino_training_extensions/pytorch_toolkit/text_spotting/venv ~/mount_disk/openvino_training_extensions/pytorch_toolkit/text_spotting
Cloning into 'vision'...
`

**Steps to Reproduce**
1. Clone the repo and `cd openvino_training_extensions/pytorch_toolkit/text_spotting`
2. run `bash init_venv.sh`

**Environment:**
 - OS: Linux Ubuntu 18.04
 - Framework version: PyTorch
 - Python version: 3.6.9
 - OpenVINO version: NA
 - CUDA/cuDNN version: No cuda
 - GPU model and memory: NA

**Comment by AlexanderDokuchaev** [comment]
Hi @ankitbansal811 
Thank you for your interest in our project.
Issue was fixed https://github.com/Ilya-Krylov/pytorch/pull/1
