### ISSUE TITLE
Why the model architecture trained by openvino training extension is different with the pretrained model which from OMZ.

### ISSUE THREAD

**Issue by FengYen-Chang** [opencv/openvino_training_extensions#316]
Hello, 

This is John. As the title mentioned, we tried to use this repo to train an [object detection - Person Vehicle Bike Detector](https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/object_detection/person-vehicle-bike-detection) sample. After converted the trained model to IR, we found its architecture is different with the `person-vehicle-bike-detection-crossroad-1016` pretrained model in OMZ. Below is a visualized model architecture of both models. (left one is trained by this repo, right one is from OMZ)

![image](https://user-images.githubusercontent.com/23442770/84853953-f1671580-b092-11ea-9a44-8bf8df9bb810.png)

![image](https://user-images.githubusercontent.com/23442770/84854446-3e97b700-b094-11ea-8f8c-3a1976e6ff29.png)

Does it lack some flags during ONNX-to-IR?

Thanks,
John

**Comment by Ilya-Krylov** [comment]
@FengYen-Chang please use export.py with —alt_ssd_export flag to reproduce model from omz. Details about the flag you can find in documentation here on github.

**Comment by FengYen-Chang** [comment]
Hi @Ilya-Krylov, 

Really thanks, and I am sorry I didn't read the document well. 

Thanks,
John
