### ISSUE TITLE
converted model inference on myriad usb stick

### ISSUE THREAD

**Issue by natxopedreira** [opencv/openvino_training_extensions#320]
Hello

I fine tuning some pytorch face models, but im getting a poor performance doing inference on intel usb stick 2. In fact doing inference on CPU intel i5 is 2x faster than doing on MYRIAD target.

I followed the instructions here
[https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/object_detection/face-detection](https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/object_detection/face-detection)

What can be wrong¿

**Comment by AlexanderDokuchaev** [comment]
Hi @natxopedreira
Which model do you use, face-detection-0100?
Did you test performance of model from [open_model_zoo](https://github.com/opencv/open_model_zoo/tree/master/models/intel/face-detection-0100)? And what performance do you have on cpu and usb stick?

But yes, usb stick is less powerful than i5. It is expected that inference on CPU can be faster in several time than on usb stick.

**Comment by natxopedreira** [comment]
@AlexanderDokuchaev 

Hi, yes i used face-detection-0100, no i didn't compare with open_model_zoo version.... will do it

On stick i get around 8fps and on CPU 14-15.... i expected to have more fps on stick :( as the plan is to use this on a rpi.

Is there anything i can do to improve it?

Thanks

**Comment by AlexanderDokuchaev** [comment]
@natxopedreira  
Try to use `export.py` with `--alt_ssd_export` option, it should improve performance.

**Comment by natxopedreira** [comment]
@AlexanderDokuchaev 

Thank you, i used that option, i have to review but i think without that flag it doesnt work....

**Comment by natxopedreira** [comment]
@AlexanderDokuchaev 

Without that flag i get a warning and later an error
```
[ WARN:0] global ../opencv/modules/dnn/src/dnn.cpp (3542) createNetworkFromModelOptimizer DNN/IE: Can't determine output layer type: '1060_1061.0'
[ WARN:0] global ../opencv/modules/dnn/src/dnn.cpp (3542) createNetworkFromModelOptimizer DNN/IE: Can't determine output layer type: 'boxes/Split.0'
[ WARN:0] global ../opencv/modules/dnn/src/dnn.cpp (3542) createNetworkFromModelOptimizer DNN/IE: Can't determine output layer type: 'boxes/Split.1'
```


`OpenCV(4.3.0-openvino-2020.3.0) ../opencv/modules/dnn/src/ie_ngraph.cpp:600: error: (-2:Unspecified error) Failed to initialize Inference Engine backend (device = MYRIAD): Failed to compile layer "536": AssertionFailed: (inputImage->desc().dims().size() == 4) && (inputImage->desc().dim(Dim::C) == 3) in function 'initPlugin'
`

**Comment by AlexanderDokuchaev** [comment]
@natxopedreira 
Inference speed on USB stick (without preprocessing and postprocessing, only time of work of model) is more than 15 fps. You have 8fps on full pipeline, right?

You can optimize your code by using asynchronous inference (example: [object_detection_demo_ssd_async.py](https://github.com/opencv/open_model_zoo/blob/master/demos/python_demos/object_detection_demo_ssd_async/object_detection_demo_ssd_async.py)).

And you can reduce input size of the model (for example to 192x192), it's increase performance through precision. 

In code:
```python
net.reshape({'input': (N,C,H,W)})
```
Or run `mo.py` with  `--input_shape [N,C,H,W]`.

**Comment by natxopedreira** [comment]
@AlexanderDokuchaev 

Those fps you mentioned are with that model?

Im doing async
`# neural feed
	in_frame = cv.resize(image, (model_w, model_h))
	in_frame = in_frame.transpose((2, 0, 1))  # Change data layout from HWC to CHW
	in_frame = in_frame.reshape((model_n, model_c, model_h, model_w))
	exec_net.start_async(request_id=0, inputs={input_blob: in_frame})

	if exec_net.requests[0].wait(-1) == 0:
		res = exec_net.requests[0].outputs[out_blob]

		for obj in res[0][0]:
			if obj[2] > 0.5:

				xmin = int(obj[3] * cap_w)
				ymin = int(obj[4] * cap_h)
				xmax = int(obj[5] * cap_w)
				ymax = int(obj[6] * cap_h)
`

**Comment by AlexanderDokuchaev** [comment]
> Those fps you mentioned are with that model?
Yes, it's face-detection-0100. You can run [benchmark_tool](https://docs.openvinotoolkit.org/latest/_inference_engine_tools_benchmark_tool_README.html) to get performance of inference.


Add to your code `net.reshape({'input': (1,3,120,160)})` before initializing `exec_net` and remove `in_frame = in_frame.reshape((model_n, model_c, model_h, model_w))`. You will avoid resize function, and inference of model will be faster.

**Comment by natxopedreira** [comment]
Thanks for your time

seems that input is not the name of the layer... how can i see layers name?

`AttributeError: Specified 'input' layer not in network inputs '{'image': <openvino.inference_engine.ie_api.DataPtr object at 0x7f5618965cf0>}'! `

**Comment by AlexanderDokuchaev** [comment]
Yeap, it' should be `image`.

**Comment by natxopedreira** [comment]
great!!!! 55fps ;)

Thank you!

**Comment by AlexanderDokuchaev** [comment]
Also you can fine tune model on target resolution.

**Comment by natxopedreira** [comment]
Nice to know, i always belive that using a different input layer size was a bad idea... im happy to be wrong.

Thank you again!
