### ISSUE TITLE
tensorflow_toolkit/lpr/  No module named 'spatial_transformer'

### ISSUE THREAD

**Issue by TNTWEN** [opencv/openvino_training_extensions#325]
train error  :"openvino_training_extensions/tensorflow_toolkit/lpr/lpr/trainer.py", line 21, in <module>
    from spatial_transformer import transformer
ImportError: No module named 'spatial_transformer'

Missing file  spatial_transformer!!!

**Comment by AlexanderDokuchaev** [comment]
HI @TNTWEN 
Looks like something go wrong when you run [prepare_modules.sh](https://github.com/opencv/openvino_training_extensions/blob/develop/tensorflow_toolkit/prepare_modules.sh). Please inspect logs.
Possible you have no installed `2to3` or `protobuf-compiler`.

**Comment by TNTWEN** [comment]
oh !I ignored `sudo apt install 2to3 protobuf-compiler` and now it works correctly
@AlexanderDokuchaev I also want to ask what kind of license plate positioning method should I choose if I use this license plate recognition.I used YOLOv3 in the previous code to identify the car. License plate recognition will be an extension of my code. Can I use YOLOV3 to identify the car and then use opencv to locate the license plate?Or is there any good method  i could use in OpenVINO
Thanks!

**Comment by AlexanderDokuchaev** [comment]
You can try to use [vehicle-license-plate-detection-barrier-0123](https://github.com/opencv/open_model_zoo/blob/master/models/public/vehicle-license-plate-detection-barrier-0123/description/vehicle-license-plate-detection-barrier-0123.md) model.

**Comment by TNTWEN** [comment]
Thanks！i use this vehicle-license-plate-detection-barrier-0123 model and write a python demo.It works great！！
