### ISSUE TITLE
Why use random earsing in cross domain testing?

### ISSUE THREAD

**Issue by L1aoXingyu** [opencv/openvino_training_extensions#327]
I notice that you use `random erasing` in [`OSNet_IAP_1_0x_msmt_all.yaml`](https://github.com/opencv/openvino_training_extensions/blob/develop/pytorch_toolkit/object_reidentification/person_reidentification/configs/experimental/OSNet_IAP_1_0x_msmt_all.yaml) as below

```
random_erase:
  enable: True
  p: 0.5
```

But it will harm the performance of cross-domain, so I want to know why you use the augmentation.

**Comment by AlexanderDokuchaev** [comment]
Hi @L1aoXingyu 

`erasing` option used only for training.

For detailed information on using transformation, see [build_test_transform](https://github.com/opencv/deep-object-reid/blob/ote/torchreid/data/transforms.py#L670) function.

**Comment by L1aoXingyu** [comment]
I know it's only used for training, but I think it will harm the generalization.

Have you seen this issue？https://github.com/KaiyangZhou/deep-person-reid/issues/221

In addition, I have this experiment table

![image](https://user-images.githubusercontent.com/19245504/88010489-9324cb00-cb47-11ea-8a2c-4ddfa8fd6068.png)

REA means random erasing.

**Comment by AlexanderDokuchaev** [comment]
@L1aoXingyu 
We have no degradation performance by using `random erasing`, on the contrary it increases metrics.
You can try to reproduce it by training own models with using our instruction and config files.

**Comment by L1aoXingyu** [comment]
Thank you. I will try it myself.
