### ISSUE TITLE
examples/classification　error

### ISSUE THREAD

**Issue by blueskywwc** [opencv/openvino_training_extensions#330]
Run the main.py of examples/classification and encountered an error: FileNotFoundError: [Errno 2] No such file or directory:'/home/sky/anaconda3/lib/python3.7/site-packages/nncf-1.3.2- py3.7.egg/nncf/extensions/src/quantization/cpu/functions_cpu.cpp',
How to deal with this error, thank you!

**Comment by AlexanderDokuchaev** [comment]
Hi @blueskywwc 
NNCF has moved to https://github.com/openvinotoolkit/nncf_pytorch repository. 
Please recreate issue in actual repository and provide more information (your configuration, how you install nncf, steps to reproduce).
